kafka:
  bootstrap-servers:
    - kafka:9092
  template:
    default-topic: helloworld.message.topic
  producer:
    keySerializer: org.springframework.kafka.support.serializer.StringSerializer
    valueSerializer: org.springframework.kafka.support.serializer.StringSerializer